<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="AmerkhanPC" failures="1" tests="9" name="tests.Manual_SKR_Regenerate" time="384.752" errors="0" timestamp="2023-08-22T15:31:40 IST" skipped="0">
  <testcase classname="tests.Manual_SKR_Regenerate" name="testAuth" time="2.715"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="testVerify2FA" time="1.420"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="getuserId" time="1.491"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="createSKR" time="1.542"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="getKeyId" time="1.389"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="getKeyDetails" time="1.389"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="keyRegenerate" time="12.212"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="getCodeDeliveryStatus" time="361.448"/>
  <testcase classname="tests.Manual_SKR_Regenerate" name="smartthingsverification" time="1.146">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at tests.Manual_SKR_Regenerate.smartthingsverification(Manual_SKR_Regenerate.java:233)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- smartthingsverification -->
</testsuite> <!-- tests.Manual_SKR_Regenerate -->
